### PR TITLE
Compatibility with thunderbird-60, fixes #55

### LINKED ISSUE #55: Compatibility with Thunderbird 60.0
It's more a feature request than an issue at this moment because the tested version of Thunderbird is in beta state, 60.0 but I can see this will become a problem in the future. Thunderbird just refuses to use this add-on. Unless there is any other reason, can someone have a look at this?

### PR DESCRIPTION
**Pull request by uli-heller**
Fixes: *#55*

Licence: AGPL3+ or any other compatible license

### Description

I tried to use nexcloud-filelink within thunderbird 60. I got it up and running
by this:

- upgrade to thunderbird 60
- existing filelink doesn't work any more
- create an xpi
    - `cd src`
    - `zip -r /tmp/fl.xpi .`
- install the xpi within thunderbird 60
- seems to work now

I used these instructions: https://wiki.mozilla.org/Thunderbird/Add-ons_Guide_57

### Tests

I tested on Linux/Thunderbird-60 only.

### TODO
-  do test on other platforms
-  do test the initial configuration of filelink

### CODE REVIEW

**Comment by creopard** [comment]
Tested and working on Windows 7(64bit) regarding the file upload :1st_place_medal: 
However displaying the "totalStorage" and "fileSpaceUsed" does not seem to work any more:

**Thunderbird 60 (broken):**
tb60

**Thunderbird 52.9.1 (working):**
tb52

**Comment by dadosch** [comment]
>do test the initial configuration of filelink

worked just fine with TB60/Linux. Howewer, like @creopard pointed out, _Used Space_ and _Unused Space_ is empty.

Additionally, the name of the provider is not shown.
screenshot_20180810_190355

**Comment by uli-heller** [comment]
Within the error console, I see these when opening the configuration dialog:

```
2018-08-13 07:49:23	Nextcloud	ERROR	Could not retrieve password
  log4moz.js:680
	CApp_append resource:///modules/gloda/log4moz.js:680:7
	Logger_log resource:///modules/gloda/log4moz.js:374:7
	Logger_error resource:///modules/gloda/log4moz.js:382:5
	nsNc_logon jar:file:///media/XXX/extensions/owncloud@viguierjust.com.xpi!/components/nsNextcloud.js:431:4
	nsNc_logonAndGetUserInfo jar:file:///media/XXX/extensions/owncloud@viguierjust.com.xpi!/components/nsNextcloud.js:717:10
	nsNc_refreshUserInfo jar:file:///media/XXXextensions/owncloud@viguierjust.com.xpi!/components/nsNextcloud.js:259:11
	CFT_requestUserInfoForItem chrome://messenger/content/preferences/applications.js:630:5
	CFT_rebuildView chrome://messenger/content/preferences/applications.js:605:9
	init chrome://messenger/content/preferences/applications.js:527:5
	init chrome://messenger/content/preferences/applications.js:414:5
	anonymous chrome://messenger/content/preferences/preferences.xml%20line%20779%20%3E%20Function:3:1
	_fireEvent chrome://messenger/content/preferences/preferences.xml:780:24
	observe
```

Maybe I do have the time to look into this during the next days...

**Comment by e-alfred** [comment]
Maybe @oparoz or @guillaumev can review this an push a new release to addons.mozilla.org?

**Comment by uli-heller** [comment]
image

**Comment by guillaumev** [comment]
I just sent some code to the master branch, which should fix the password issue and also fix the file upload issue (I'm not yet sure it fixes the space issue however). Could some people try it and let me know ? Thank you

**Pull request merged**
