### PR TITLE
Finish french translation for the about view

### PR DESCRIPTION
**Pull request by tbille**
Licence: AGPL3+ or any other compatible license

### Description

Finish french translation for the about view

### Screenshots or screencasts

a propos de l extension nextcloud pour filelink_004

### CODE REVIEW

**Comment by oparoz** [comment]
:+1: 
Thank you @tbille. Looks good. I just need to test it to see if it's accepted as I've had issues in the past with some strings in the XML :)

**Comment by tbille** [comment]
okay, I forgot to translate the `install.rdf` I'll do it in another pull-request :)

**Comment by oparoz** [comment]
You can simply add another commit to this one, unless it's because of a technical issue on your side?

**Comment by tbille** [comment]
Finally I added it here, it was simply to keep the sense of the description of the pull request.

**Comment by oparoz** [comment]
> Finally I added it here, it was simply to keep the sense of the description of the pull request.

Yeah, I understand, but I think it's OK this time :)

**Pull request merged**
